# Generated by Django 5.2.1 on 2025-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
