# Generated by Django 5.2.1 on 2025-06-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='diary_access_blocked',
            new_name='is_diary_blocked',
        ),
    ]
